// Generated by Dagger (https://dagger.dev).
package com.ilongyuan.lysdk.dagger;

import com.ilongyuan.lysdk.repository.DataRepository;
import com.ilongyuan.lysdk.service.impl.ServiceImpl;

import javax.inject.Provider;

import dagger.MembersInjector;

@SuppressWarnings({
        "unchecked",
        "rawtypes"
})
public final class ServiceImpl_MembersInjector implements MembersInjector<ServiceImpl> {
    private final Provider<DataRepository> dataRepositoryProvider;

    public ServiceImpl_MembersInjector(Provider<DataRepository> dataRepositoryProvider) {
        this.dataRepositoryProvider = dataRepositoryProvider;
    }

    public static MembersInjector<ServiceImpl> create(
            Provider<DataRepository> dataRepositoryProvider) {
        return new ServiceImpl_MembersInjector(dataRepositoryProvider);
    }

    public static void injectDataRepository(ServiceImpl instance, DataRepository dataRepository) {
        instance.dataRepository = dataRepository;
    }

    @Override
    public void injectMembers(ServiceImpl instance) {
        injectDataRepository(instance, dataRepositoryProvider.get());
    }
}
